### ISSUE TITLE
Build fails when running build_locally.sh due to /assets/js/tests/report-test.js failure

### ISSUE THREAD

**Issue by mallen47** [mwinteringham/restful-booker-platform#230]
Hi there! I just purchased a copy of the Testing Web APIs book and I'm excited to get started working through the examples. However, I stumbled right out of the blocks when attempting to build locally. On a Mac (12.6.2 Mac OS Monterey) upon running ```bash build_localy.sh```, the build fails due to the following failed test:

```
FAIL tests/report-test.js (5.833 s)
  ● Multiple reports can be created in the Report component

    TestingLibraryElementError: Unable to find an element with the text: /103/. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.

    ...

 34 |
      35 |     await waitFor(() => {expect(mockReport.isDone()).toBeTruthy()})
    > 36 |     await getByText(/103/)
         |           ^
      37 |
      38 |     expect(asFragment()).toMatchSnapshot();
      39 | });

      at Object.getElementError (node_modules/@testing-library/dom/dist/config.js:37:19)
      at node_modules/@testing-library/dom/dist/query-helpers.js:76:38
      at node_modules/@testing-library/dom/dist/query-helpers.js:52:17
      at node_modules/@testing-library/dom/dist/query-helpers.js:95:19
      at getByText (tests/report-test.js:36:11)
      at tryCatch (node_modules/@babel/runtime/helpers/regeneratorRuntime.js:44:17)
      at Generator.<anonymous> (node_modules/@babel/runtime/helpers/regeneratorRuntime.js:125:22)
      at Generator.next (node_modules/@babel/runtime/helpers/regeneratorRuntime.js:69:21)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:9)
```

I've attemped to remove ```node_modules``` and ```package-lock.json``` followed by ```npm-install```.  Then I tried running the ```js``` tests with ```npm test``` and got the following error for ```report-test.js```:

```
 FAIL  tests/report-test.js
  ● Multiple reports can be created in the Report component

    expect(received).toMatchSnapshot()

    Snapshot name: `Multiple reports can be created in the Report component 1`

    - Snapshot  - 2
    + Received  + 2

    @@ -162,11 +162,11 @@
                      >
                        31
                      </button>
                    </div>
                    <div
    -                 class="rbc-date-cell"
    +                 class="rbc-date-cell rbc-current"
                      role="cell"
                    >
                      <button
                        class="rbc-button-link"
                        role="cell"
    @@ -174,11 +174,11 @@
                      >
                        01
                      </button>
                    </div>
                    <div
    -                 class="rbc-date-cell rbc-current"
    +                 class="rbc-date-cell"
                      role="cell"
                    >
                      <button
                        class="rbc-button-link"
                        role="cell"

      36 |     await getByText(/103/)
      37 |
    > 38 |     expect(asFragment()).toMatchSnapshot();
         |                          ^
      39 | });
      40 |

      at toMatchSnapshot (tests/report-test.js:38:26)
      at tryCatch (node_modules/@babel/runtime/helpers/regeneratorRuntime.js:44:17)
      at Generator.<anonymous> (node_modules/@babel/runtime/helpers/regeneratorRuntime.js:125:22)
      at Generator.next (node_modules/@babel/runtime/helpers/regeneratorRuntime.js:69:21)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:9)

```

Also, I noticed when running ```npm install``` there were "3 high severity vulnerabilities". Not sure if that is related to the test failure or a separate issue. Here is the output from ```npm audit``` showing the warning info:

```
➜  js git:(trunk) ✗ npm install

up to date, audited 1254 packages in 3s

121 packages are looking for funding
  run `npm fund` for details

3 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
➜  js git:(trunk) ✗ npm audit
# npm audit report

json5  <1.0.2
Severity: high
Prototype Pollution in JSON5 via Parse Method - https://github.com/advisories/GHSA-9c47-m6qq-7p4h
fix available via `npm audit fix --force`
Will install babel-core@4.7.16, which is a breaking change
node_modules/babel-core/node_modules/json5
  babel-core  5.8.20 - 7.0.0-beta.3
  Depends on vulnerable versions of babel-register
  Depends on vulnerable versions of json5
  node_modules/babel-core
    babel-register  *
    Depends on vulnerable versions of babel-core
    node_modules/babel-register

3 high severity vulnerabilities
To address all issues (including breaking changes), run:
  npm audit fix --force
```

Here's my system info:
```
Mac OS Monterey v12.6.2

java --version
java 18.0.2.1 2022-08-18
Java(TM) SE Runtime Environment (build 18.0.2.1+1-1)
Java HotSpot(TM) 64-Bit Server VM (build 18.0.2.1+1-1, mixed mode, sharing)

mvn --version
Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: /Users/mattallen/dev/maven/apache-maven-3.8.6
Java version: 18.0.2.1, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk-18.0.2.1.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "12.6.2", arch: "x86_64", family: "mac"

node -v
v18.13.0

npm -v
8.19.3
```

I am able to get the build up and running by simply skipping this failing test, but figured it would be helpful to others if the test was fixed. Thanks!

**Comment by mwinteringham** [comment]
Hi @mallen47 

Thanks for letting me know about this. I will be doing a dependency update soon so I'll look into this and see what is going on.

**Comment by mwinteringham** [comment]
Duplicate of #225 ?

**Comment by mwinteringham** [comment]
The issue with this test has now been fixed.

**Comment by mallen47** [comment]
Thank you Mark!
